### ISSUE TITLE
command not found?

### ISSUE THREAD

**Issue by izgzhen** [s92025592025/CSE403-Wi19-Flint#20] opened 2019-02-14 02:09 UTC
```
➜  Flint-CLI-Distribution-master sh ./flint.sh -config-path . -config-class FlintConfig403 -file-path FlintConfig403.java  
: command not found 
: command not found 
: command not found 
./flint.sh: line 14: syntax error: unexpected end of file
```

**Comment by s92025592025** [comment] 2019-02-14 02:12
@izgzhen Can I have the current system you are using?

**Comment by izgzhen** [comment] 2019-02-14 02:53
> @izgzhen Can I have the current system you are using?

I am using macOS

> What have you tried before this script errored out?

I think nothing? this `: command not found` thing is also confusing and I failed to debug it in one minute, so opening the issue here.

**Comment by s92025592025** [comment] 2019-02-14 04:40
@izgzhen This issue should be fixed by now.

For reference, this is caused by the line ending difference on windows and unix systems

**Closed by s92025592025** 2019-02-14 04:40 UTC
